version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:10
    working_directory: ~/project
    environment:
      YARN_CACHE_FOLDER: "~/.cache/yarn"

commands:
  attach_project:
    steps:
      - attach_workspace:
          at: ~/project

jobs:
  install-dependencies:
    executor: default
    steps:
      - checkout
      - attach_project
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install project dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths: .

  lint:
    executor: default
    steps:
      - attach_project
      - run:
          name: Lint files
          command: yarn lint
      - run:
          name: Prettier (for TS files)
          command: |
            yarn prettier --list-different "**/*.js" "**/*.ts"

  test:
    executor: default
    steps:
      - attach_project
      - run:
          name: Run unit tests
          command: yarn test --maxWorkers=2 --coverage
      - run:
          name: Upload test coverage
          command: yarn codecov
      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  lint-and-test:
    jobs:
      - lint:
          requires:
            - install-dependencies
      - test:
          requires:
            - install-dependencies
